db_uri = "data.sqlite"
# https_proxy = "socks5h://127.0.0.1:1080"
tmdb_secret = "tmdb_secret"
link_to = '/some/emby/path'

# 邮件通知设置
[email]
sender = "123456@qq.com"
sender_pswd = "abcfasdfoer"
smtp_host = "smtp.qq.com"
receiver = "example@gmail.com"

# qb 设置
[qb]
base_url = "http://127.0.0.1:8080"
username = "admin"
password = "adminadmin"

[gpt]
url = "https://api.openai.com/v1"
token = "sk-xxxx"
model = "gpt-3.5-turbo-0125"
retry = 3
better_model = "gpt-4-turbo"
better_since = 4

# RSS 订阅
[[feed]]
name = "秒杀外挂"
type = "rss"
site = "comicat"
search = "秒杀外挂"
savepath = '/download/anime/'
# interval_s = 900 # 默认 15 分钟刷新一次
# content_layout = 'NoSubfolder'
# category = "BT"
# tags = ["动漫花园", "测不准的阿波连同学", "动画"]    # qb 的标签
# auto_torrent_management = false # 是否使用 qb 的自动种子管理
# filters = ["S05E[123]", "CAKES$"] # 正则
# not_filters = ["REPACK"] # regex
