db_uri = "data.sqlite"

[qb]
base_url = "http://127.0.0.1:8080"
username = "admin"
password = "adminadmin"

[[feed]]
name = "动漫花园 - 阿波连"
url = "https://dmhy.anoneko.com/topics/rss/rss.xml?keyword=%E9%98%BF%E6%B3%A2%E8%BF%9E&sort_id=0&team_id=657&order=date-desc"
savepath = "/downloads/anime/测不准的阿波连同学 (2022)"
category = "BT"
tags = ["动漫花园", "测不准的阿波连同学", "动画"]
